- name: variables
  hosts: local
  connection: local
  vars: # Play level variables
    COURSE: "Devops with AWS"
    DURATION: 120hrs
    TRAINER: Mahe
  tasks:
  - name: Printing variables
    vars: # Tasks level variables
    ansible.builtin.debug:
      COURSE: Ansible
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER}}"

  - name: Printing variables
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER}}"