- name: Install Application
  hosts: web
  become: yes
  tasks:
  - name: Install mginx if RHEL
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family == "RedHat"  # condition to check which OS. This is taken from facts.json file

  - name: Install nginx if Ubuntu
    ansible.builtin.apt:
      name: nginx
      state: installed
    when: ansible_os_family == "Debian"

