- name: Install packages
  hosts: web
  become: yes
  tasks:
  - name: Install applications
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - nginx
    - mysql
    - gcc