- name: Install and uninstall packages
  hosts: web
  become: yes
  tasks:
  - name: Install and uninstall applications in loop
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'nginx', state: 'present' }
    - { name: 'mysql', state: 'absent' }
    - { name: 'gcc', state: 'present' }