- name: Print default variable - filters
  hosts: local
  connection: local
  tasks:
  - name: Print default variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Ramesh') }}"


  - name: Convert string to list
    vars:
      fruits: "apple, banana, orange"  # string
    ansible.builtin.debug:
      msg: "fruits are: {{ fruits | split(',') }}"
      

  - name: convert map to list
    vars:
      course:
        name: devops
        duration: 1210hrs
        Trainer: Siva
    ansible.builtin.debug:
      msg: "courses info: {{ course | dic2items }}"


  - name: convert list to map
    vars:
      course:
      - { key: name, value: ansible }
      - { key: duration, value: 120hrs }
      - { key: Trainer, value: siva }
    ansible.builtin.debug:
      msg: "course info: {{ course | items2dict }}"

  - name: convert to upper case
    vars:
      name: "Mahender"
    ansible.builtin.debug:
      msg: "upper case: {{ name | upper }}"
      
  - name: convert to lower case
    vars:
      name: "Mahender"
    ansible.builtin.debug:
      msg: "lower case: {{ name | lower }}"

